### ISSUE TITLE
HTML Showing up when Image Added

### ISSUE THREAD

**Issue by bgiesing** [camporez/camporez.github.io#32]
When adding an image and using the `master` branch, raw HTML code shows above the image in the header.

[An example can be seen in this post.][1]

Here is what shows up:
```html
"/media/2015-01-15-hss-turbine-facets/cover.png"}" /> "/media/2015-01-15-hss-turbine-facets/cover.png"}" />
```

[You can view the code here.][2]

Any ideas?

[1]: http://brandon.giesing.cf/hss-turbine-facets/
[2]: https://github.com/bgiesing/bgiesing.github.io

**Comment by bgiesing** [comment]
I just figured out how to fix it and submitted a pull request! @ianbrunelli 

camporez/Thinny#10

**Comment by bgiesing** [comment]
I found the fix!

As shown in this commit, ac5194410c2ec650a7cbfc853a50d57853bfa393, you need to add `.url` to every instance of `page.image` or `page.next.image` to make it `page.image.url` or `page.next.image.url`!

@ianbrunelli

**Comment by ianbrunelli** [comment]
Hey, thanks for this, and sorry for the late answer.

I'm looking forward for your next PR.

**Comment by bgiesing** [comment]
@ianbrunelli just submitted the new Pull Request

**Comment by ianbrunelli** [comment]
It looks good.

I think it was already implemented in camporez.github.io repo, but I forgot to add this here.

Thank you very much :D
